### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jeenyuhs** [RealistikOsu/Kisumi#2]
its not working! fix yopur code! i expect 1:1 copy of bancho when i revisit this repository (in 2 hours)

**Comment by RealistikDash** [comment]
Greetings kind sir. Unfortunately, your expectations are as unrealistic as Denmark. Please up the time to 3 hours.

**Comment by VIPERSON22** [comment]
anyone want to play gran turismo with me?

**Comment by xSkyyy** [comment]
> Greetings kind sir. Unfortunately, your expectations are as unrealistic as Denmark. Please up the time to 3 hours.

unrealistik

**Comment by jeenyuhs** [comment]
> > Greetings kind sir. Unfortunately, your expectations are as unrealistic as Denmark. Please up the time to 3 hours.
> 
> unrealistik

Please do not reply to this thread. It's made for RealistikOsu, not you. Your IP is 127.0.0.1; I have your family.

**Comment by xSkyyy** [comment]
fuck you

**Comment by jeenyuhs** [comment]
> fuck you
> 

Please do not speak to me, as your just as annoying as Skyler from Breaking Bad, Skylar.

**Comment by xSkyyy** [comment]
why so accurate

**Comment by jeenyuhs** [comment]
Because, my name is Walter Hartwell White. I live at 308 Negra Aroya Lane, Albuquerque, New Mexico, 87104.

**Comment by VIPERSON22** [comment]
anyone want to play chess?

**Comment by Maccama** [comment]
when

**Comment by VIPERSON22** [comment]
now
